version: '3.5'
services:
    currency-tracking:
        hostname: currency-tracking-php
        build: docker/php-fpm
        container_name: currency-tracking-php
        volumes:
            - ./:/var/www/app
        expose:
            - 9000
        networks:
            - app-network

    currency-tracking-nginx:
        hostname: currency-tracking-nginx
        build: docker/nginx
        container_name: currency-tracking-nginx
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - currency-tracking
        networks:
            - app-network

    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: qwerty123
            MYSQL_DATABASE: currency_tracking_db
            MYSQL_USER: user
            MYSQL_PASSWORD: qwerty123
        ports:
            - "3306:3306"
        restart: on-failure
        networks:
            - app-network

    rabbitmq:
        hostname: currency-tracking-rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - "RABBITMQ_DEFAULT_USER=guest"
            - "RABBITMQ_DEFAULT_PASS=guest"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
